
-- exercise 2 
USE LAB6;

CREATE OR REPLACE TRIGGER SumImp
AFTER UPDATE OF JOB ON IMP  
FOR EACH ROW
DECLARE 
N INT;
M INT;

BEGIN
    SELECT COUNT(*) INTO N 
    FROM SUMMARY
    WHERE JOB = NEW.JOB;

IF (N = 0) THEN
    INSERT INTO SUMMARY (JOB, NUM)
    VALUES (:NEW.JOB, 1);
ELSE 
    UPDATE SUMMARY
    SET NUM = NUM + 1;
    WHERE JOB = :NEW.JOB;
END IF;

SELECT NUM INTO M 
FROM SUMMARY
WHERE JOB = OLD.JOB;

IF (M = 0) THEN
    DELETE FROM SUMMARY
    WHERE JOB = :OLD.JOB;
ELSE 
    UPDATE SUMMARY
    SET NUM = NUM -1;
    WHERE JOB = :OLD.JOB 
END IF;
END;


CREATE OR REPLACE TRIGGER SumImp
AFTER  INSERT ON IMP 
FOR EACH ROW
DECLARE 
N NUMBER;
M NUMBER;

BEGIN
    SELECT COUNT(*) INTO N 
    FROM SUMMARY
    WHERE JOB = OLD.JOB;

    

IF (N = 0) THEN
    INSERT INTO SUMMARY (JOB, NUM)
    VALUES (:NEW.JOB, 1);
ELSE 
    UPDATE SUMMARY
    SET NUM = NUM + 1
    WHERE JOB = :NEW.JOB;
END IF;
END;


