SET storage_engine=InnoDB;
SET FOREIGN_KEY_CHECKS=1;
CREATE DATABASE IF NOT EXISTS LAB6;

DROP TABLE IF EXISTS IMP;
DROP TABLE IF EXISTS SUMMARY;

CREATE TABLE IMP
(EMPNO INT,
ENAME VARCHAR(10),
JOB VARCHAR(10),
SAL INT,
PRIMARY KEY(EMPNO));


CREATE TABLE SUMMARY
(JOB VARCHAR(10),
NUM INT,
PRIMARY KEY(JOB));

USE LAB6;


INSERT INTO IMP(EMPNO, ENAME, JOB, SAL) 
VALUES(1, 'VERDI', 'SECRETARY', 800);

INSERT INTO IMP(EMPNO, ENAME, JOB, SAL) 
VALUES(2, 'ROSSI', 'BANKER', 900);

INSERT INTO IMP(EMPNO, ENAME, JOB, SAL) 
VALUES(3, 'BIANCHI', 'BANKER', 1100);


INSERT INTO SUMMARY(JOB,NUM)
VALUES('SECRETARY',1);

INSERT INTO SUMMARY(JOB,NUM)
VALUES('BANKER',2);